name: Tests

on:
  - pull_request:
      branches:
        - main

jobs:
  test:
    name: Run tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Create artifacts dir
        run: mkdir artifacts
      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin'
      - name: Run tests
        run: mvn -P test test > artifacts/test_logs.txt
      - name: Upload artifacts
        uses: actions/upload-artifact@v1
        if: always()
        with:
          name: test_artifacts
          path: artifacts